version: "3.8"
services:
  python:
    build: ./python_redis
    links:
      - redis
    container_name: python_redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: rediska
